#+BEGIN_COMMENT
.. title: Ffmpeg wasm
.. slug: ffmpeg-wasm
.. date: 2020-11-29 23:11:20 UTC+09:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
.. author: Duc To
#+END_COMMENT

* Introduction

Ffmpeg wasm is a pure Webassembly / Javascript port of FFmpeg. It enables video & audio record, convert and stream right inside browsers.

The main Git repository for it is https://github.com/ffmpegwasm/ffmpeg.wasm

* Licensing

- @ffmpeg/ffmpeg contains kind of a wrapper to handle the complexity of loading core and calling low-level APIs. It is a small code base and under MIT license.

- @ffmpeg/core following the same licenses as FFmpeg and its external libraries.

* How it works

- The only js file defined in html file is https://unpkg.com/@ffmpeg/ffmpeg@0.9.4/dist/ffmpeg.min.js but actually it is just a wrapper.
- Based on the actual need in our triggered ffmpeg function, the js will load ffmpeg/core file ffmpeg-core.wasm and its js file ffmpeg-core.js. ffmpeg-core.wasm's file size at the time of testing is 22MB.
- Sometimes we may need to use the newest version of @ffmpeg/core and we can define it using customized path.

#+BEGIN_SRC javascript
const ffmpeg = createFFmpeg({
  corePath: '../../../src/ffmpeg-core.js',
});
#+END_SRC

- We can re-compile ffmpeg-core by checking build.sh inside https://github.com/ffmpegwasm/ffmpeg.wasm-core repository.

* Testing result

- We made 3 test cases converting from h265 video file, mov file which recorded from MacOS and a sample move file which we get from the internet to MP# format:
  - Convert the h265 format file in this ticket to mp4. It is successful but the progress takes very long to complete, more than 6 mins while if we do it with ffmpeg command it is just around 3 mins. So nearly double the time.
  - Convert admin_sort mov video, which I think that you recorded it on Mac device to mp4 format. It is failed after few seconds using ffmpeg wasm library but it is successful using ffmpeg command.
  - Convert the mov video which I downloaded from the internet to mp4 format. It is successful and the conversion time is quite fast, around 2 mins.

At the moment of writting this article, ffmpeg wasm is twice slower and unstable, but it is worth monitoring the future progress and we may use WASM ImageMagic in future.
